language: node_js
sudo: false
node_js:
  - '5'
  - '4'
  - '0.12'
  - '0.10'
before_install:
  - npm install -g grunt-cli
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-amd' ]; then cd .. && eval "mv $currentfolder generator-amd" && cd generator-amd; fi
before_script:
  - grunt